#!/usr/bin/env python3
# rewritten encore.sh
import sys
import os
import wget

from functions import *

if not os.geteuid() == 0:
    sys.exit("\nYOU SHALL NOT PASS. you have to be rootn")


def show_help():
    print("encore [write] [read] [destroy] [initialize]")
    print("[update] [version] \n")
    print("encore write FILE name owner \n")
    print("encore read name owner \n")
    print("encore destroy name owner \n")
    print("encore initialize **WARNING THIS WILL DELETE ANY STORED DATA AND KEYS** \n")
    # print("encore  backup *Not implemented yet*")
    if version == "V1.50":
        print("encore update just performs a wellness test \n")
    else:
        print("encore update performs system wellness test then downloads the lates version of encore \n")


action = str(sys.argv[1])

if action == "write":

    path = str(sys.argv[2])
    real_path = os.path.realpath(path)
    object_class = str(sys.argv[3])
    object_item = str(sys.argv[4])

    exists = os.path.exists(real_path)
    if exists == True:
        check_keys()
        fwrite(real_path, object_class, object_item)
    else:
        sys.exit("File name given does not exists")

elif action == "read":

    object_class = str(sys.argv[2])
    object_item = str(sys.argv[3])

    check_keys()
    fread(object_class, object_item)

elif action == "destroy":

    object_class = str(sys.argv[2])
    object_item = str(sys.argv[3])

    destroy(object_class, object_item)

elif action == "initialize":

    initialize()

elif action == "debug":

    action_2 = str(sys.argv[2])

    if action_2 == "json":

        print("debug_json", object_class, object_item)

    else:

        print("echo neither of us know where start here")


elif action == "update":

    if os.path.exists("/tmp/install.sh"):
        os.remove("/tmp/install.sh")
    else:
        relazy()

    url = str("https://raw.githubusercontent.com/Dj-Codeman/encryption-core/master/install.sh")
    filename = wget.download(url, out="/tmp/install.sh")

    # count the variables set
    arguments = int(len(sys.argv))

    if arguments == 3:
        option = str(sys.argv[2])

        if option == "force":
            command = f"/bin/bash {filename} {option}"
            os.system(command)
        else :
            sys.exit("\nInvalid keyword for update ",option,"\n")

    else:
        command = f"/bin/bash {filename}"
        os.system(command)

elif action == "version":
    print("Version:", version)

elif action == "help":

    print("Version:", version, "\n")
    show_help()

else:

    show_help()

exit()
